-- Core schema: users, venues, events, ticket types.
-- Postgres profile only; the dev H2 profile uses Hibernate create-drop.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,
    version       BIGINT       NOT NULL
);

CREATE TABLE venue (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(150) NOT NULL,
    address  VARCHAR(250) NOT NULL,
    city     VARCHAR(100) NOT NULL,
    capacity INTEGER      NOT NULL,
    version  BIGINT       NOT NULL
);

CREATE TABLE event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200)  NOT NULL,
    description  VARCHAR(2000),
    venue_id     BIGINT        NOT NULL REFERENCES venue (id),
    organizer_id BIGINT        NOT NULL REFERENCES app_user (id),
    starts_at    TIMESTAMPTZ   NOT NULL,
    ends_at      TIMESTAMPTZ   NOT NULL,
    status       VARCHAR(20)   NOT NULL,
    created_at   TIMESTAMPTZ   NOT NULL,
    version      BIGINT        NOT NULL
);
CREATE INDEX idx_event_status ON event (status);
CREATE INDEX idx_event_organizer ON event (organizer_id);

CREATE TABLE ticket_type (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id           BIGINT      NOT NULL REFERENCES event (id),
    name               VARCHAR(100) NOT NULL,
    price_cents        BIGINT      NOT NULL,
    currency           VARCHAR(3)  NOT NULL,
    quantity_total     INTEGER     NOT NULL,
    quantity_available INTEGER     NOT NULL,
    version            BIGINT      NOT NULL
);
CREATE INDEX idx_ticket_type_event ON ticket_type (event_id);
