-- Bookings and their line items.

CREATE TABLE booking (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id          BIGINT      NOT NULL REFERENCES event (id),
    attendee_id       BIGINT      NOT NULL REFERENCES app_user (id),
    status            VARCHAR(20) NOT NULL,
    total_cents       BIGINT      NOT NULL,
    currency          VARCHAR(3)  NOT NULL,
    payment_reference VARCHAR(100),
    created_at        TIMESTAMPTZ NOT NULL,
    expires_at        TIMESTAMPTZ,
    version           BIGINT      NOT NULL
);
CREATE INDEX idx_booking_attendee ON booking (attendee_id);
CREATE INDEX idx_booking_event ON booking (event_id);
-- Supports the stale-hold sweep: WHERE status = 'PENDING' AND expires_at < now().
CREATE INDEX idx_booking_status_expires ON booking (status, expires_at);

CREATE TABLE booking_item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id       BIGINT  NOT NULL REFERENCES booking (id),
    ticket_type_id   BIGINT  NOT NULL REFERENCES ticket_type (id),
    quantity         INTEGER NOT NULL,
    unit_price_cents BIGINT  NOT NULL
);
CREATE INDEX idx_booking_item_booking ON booking_item (booking_id);
